apiVersion: v1
kind: Pod
metadata:
  name: snowflake-check
  namespace: airflow
spec:
  restartPolicy: Never
  containers:
  - name: snowflake-check
    image: python:3.10-slim
    envFrom:
    - secretRef:
        name: snowflake-creds
    command: ["/bin/bash", "-c"]
    args:
    - |
      pip install snowflake-connector-python &&
      python -c "
      import snowflake.connector
      import os
      
      print('🔍 Checking Snowflake database...')
      conn = snowflake.connector.connect(
          account=os.environ['SNOWFLAKE_ACCOUNT'],
          user=os.environ['SNOWFLAKE_USER'],
          password=os.environ['SNOWFLAKE_PASSWORD'],
          database=os.environ['SNOWFLAKE_DATABASE'],
          warehouse=os.environ['SNOWFLAKE_WAREHOUSE'],
          schema='RAW',
          role=os.environ['SNOWFLAKE_ROLE']
      )
      
      cursor = conn.cursor()
      
      try:
          cursor.execute('SELECT COUNT(*) FROM RAW_EVENTS')
          count = cursor.fetchone()[0]
          print(f'📊 Total records in RAW_EVENTS table: {count}')
          
          if count > 0:
              cursor.execute('SELECT * FROM RAW_EVENTS LIMIT 3')
              rows = cursor.fetchall()
              print('📋 Sample data structure:')
              for i, row in enumerate(rows, 1):
                  print(f'  {i}. {row}')
                  
              # Check column names
              cursor.execute('DESCRIBE TABLE RAW_EVENTS')
              columns = cursor.fetchall()
              print('📝 Table structure:')
              for col in columns:
                  print(f'  {col[0]}: {col[1]}')
          else:
              print('❌ RAW_EVENTS table is EMPTY!')
              
      except Exception as e:
          print(f'❌ Error accessing RAW_EVENTS: {e}')
          cursor.execute('SHOW TABLES')
          tables = cursor.fetchall()
          print('Available tables in RAW schema:')
          for table in tables:
              print(f'  {table[1]}')
      
      cursor.close()
      conn.close()
      print('✅ Database check completed.')
      "
