# k8s/producer-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-producer-deployment
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-producer
  template:
    metadata:
      labels:
        app: github-producer
    spec:
      containers:
      - name: producer
        image: github-producer:v1
        imagePullPolicy: IfNotPresent
        command: ["python", "producer.py"]
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: GITHUB_TOKEN
        # Use the simple, in-namespace Kafka address
        - name: KAFKA_BROKER
          value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: producer-metrics-svc
  namespace: airflow
spec:
  selector:
    app: github-producer
  ports:
  - name: metrics
    port: 8000
    targetPort: 8000
  type: NodePort